spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: maria@12yarmole
    url: jdbc:postgresql://localhost:5432/movieland

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true